/**********************************************************************************************************************
 * \file GPIO_LED_Button.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *
 *********************************************************************************************************************/
/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "IfxPort.h"

/*********************************************************************************************************************/
/*-----------------------------------------------------Macros--------------------------------------------------------*/
/*********************************************************************************************************************/
#define LED1     &MODULE_P00,5   /* Port pin for the LED     */
#define LED2     &MODULE_P00,6
#define BUTTON1  &MODULE_P00,7

#define a1     &MODULE_P00,0
#define a2     &MODULE_P00,1
#define a3     &MODULE_P00,2
#define a4     &MODULE_P00,3
#define a5     &MODULE_P00,8
#define a6     &MODULE_P00,9
#define a7     &MODULE_P00,10
#define a8     &MODULE_P00,11

int a=0;
int aec[8]={0,};
int aec_a[8]={0,};

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
/* Function to configure the port pins for the push button and the LED */
void init_GPIOs(void)
{
    /* Setup the port pin connected to the LED to general output mode push-pull. This function can be used
     * to initialize any port pin by specifying the port number, pin number and port pin mode.
     */
//    IfxPort_setPinMode(LED1, IfxPort_Mode_outputPushPullGeneral);
 //   IfxPort_setPinMode(LED2, IfxPort_Mode_outputPushPullGeneral);

    /* Setup the port pin connected to the push button to input mode. This function can be used to initialize any
     * port to input mode by just specifying the port number as illustrated.
     */
    IfxPort_setPinMode(LED1, IfxPort_Mode_outputPushPullGeneral);
    IfxPort_setPinMode(LED2, IfxPort_Mode_outputPushPullGeneral);
    IfxPort_setPinMode(BUTTON1, IfxPort_Mode_inputPullUp);

}

/* Depending on the the state of the "BUTTON" port pin, the LED is turned on or off */
int control_LED(void)
{
    /* With the routine getPinState() the value of a particular pin can be retrieved. This
     * function can be used to retrieve any port state by just specifying the port number
     * as illustrated.
     */
    if(IfxPort_getPinState(BUTTON1) == 0){
        IfxPort_setPinState(LED1, IfxPort_State_low);
        IfxPort_setPinState(LED2, IfxPort_State_high);
        a=0;
    }
    else    {
        IfxPort_setPinState(LED1, IfxPort_State_high);
        IfxPort_setPinState(LED2, IfxPort_State_low);
        a=1;
    }

    return a;
}

void pinmode_out(void){
    IfxPort_setPinMode(a1, IfxPort_Mode_outputPushPullGeneral);
    IfxPort_setPinMode(a2, IfxPort_Mode_outputPushPullGeneral);
    IfxPort_setPinMode(a3, IfxPort_Mode_outputPushPullGeneral);
    IfxPort_setPinMode(a4, IfxPort_Mode_outputPushPullGeneral);
    IfxPort_setPinMode(a5, IfxPort_Mode_outputPushPullGeneral);
    IfxPort_setPinMode(a6, IfxPort_Mode_outputPushPullGeneral);
    IfxPort_setPinMode(a7, IfxPort_Mode_outputPushPullGeneral);
    IfxPort_setPinMode(a8, IfxPort_Mode_outputPushPullGeneral);
    aec[8]={0,0,0,0,0,0,0,0};
    aec_a[8]={0,0,0,0,0,0,0,0};

}

void pinmode_in(void){
    IfxPort_setPinMode(a1, IfxPort_Mode_inputPullUp);
    IfxPort_setPinMode(a2, IfxPort_Mode_inputPullUp);
    IfxPort_setPinMode(a3, IfxPort_Mode_inputPullUp);
    IfxPort_setPinMode(a4, IfxPort_Mode_inputPullUp);
    IfxPort_setPinMode(a5, IfxPort_Mode_inputPullUp);
    IfxPort_setPinMode(a6, IfxPort_Mode_inputPullUp);
    IfxPort_setPinMode(a7, IfxPort_Mode_inputPullUp);
    IfxPort_setPinMode(a8, IfxPort_Mode_inputPullUp);
    aec[8]={0,0,0,0,0,0,0,0};
    aec_a[8]={0,0,0,0,0,0,0,0};
}

void outdata(int n){
    if(n>128){
        aec[7]=1;
        n=n-128;
    }
    else{aec[7]=0;}

    if(n>64){
        aec[6]=1;
        n=n-64;
    }
    else{aec[6]=0;}

    if(n>32){
        aec[5]=1;
        n=n-32;
    }
    else{aec[5]=0;}

    if(n>16){
        aec[4]=1;
        n=n-16;
    }
    else{aec[4]=0;}

    if(n>8){
        aec[3]=1;
        n=n-8;
    }
    else{aec[3]=0;}

    if(n>4){
        aec[2]=1;
        n=n-4;
    }
    else{aec[2]=0;}

    if(n>2){
        aec[1]=1;
        n=n-2;
    }
    else{aec[1]=0;}

    if(n==1){
        aec[0]=1;
        n=n-8;
    }
    else{aec[0]=0;}

    if(aec[0]==1){IfxPort_setPinState(a1, IfxPort_State_high);}else{IfxPort_setPinState(a1, IfxPort_State_low);}
    if(aec[1]==1){IfxPort_setPinState(a2, IfxPort_State_high);}else{IfxPort_setPinState(a2, IfxPort_State_low);}
    if(aec[2]==1){IfxPort_setPinState(a3, IfxPort_State_high);}else{IfxPort_setPinState(a3, IfxPort_State_low);}
    if(aec[3]==1){IfxPort_setPinState(a4, IfxPort_State_high);}else{IfxPort_setPinState(a4, IfxPort_State_low);}
    if(aec[4]==1){IfxPort_setPinState(a5, IfxPort_State_high);}else{IfxPort_setPinState(a5, IfxPort_State_low);}
    if(aec[5]==1){IfxPort_setPinState(a6, IfxPort_State_high);}else{IfxPort_setPinState(a6, IfxPort_State_low);}
    if(aec[6]==1){IfxPort_setPinState(a7, IfxPort_State_high);}else{IfxPort_setPinState(a7, IfxPort_State_low);}
    if(aec[7]==1){IfxPort_setPinState(a8, IfxPort_State_high);}else{IfxPort_setPinState(a8, IfxPort_State_low);}
}

int indata(void){
    int sum=0;

    if(a1==0){aec_a[0]=0;}else{aec_a[0]=1;}
    if(a2==0){aec_a[1]=0;}else{aec_a[1]=2;}
    if(a3==0){aec_a[2]=0;}else{aec_a[2]=4;}
    if(a4==0){aec_a[3]=0;}else{aec_a[3]=8;}
    if(a5==0){aec_a[4]=0;}else{aec_a[4]=16;}
    if(a6==0){aec_a[5]=0;}else{aec_a[5]=32;}
    if(a7==0){aec_a[6]=0;}else{aec_a[6]=64;}
    if(a8==0){aec_a[7]=0;}else{aec_a[7]=128;}

    for(int i=0; i<8; i++){
        sum += aec_a[i];
    }

    return sum;
}


